### ISSUE TITLE
Unable to create Zones | NXOS 8.4(2)

### ISSUE THREAD

**Issue by kzersatz** [Cisco-SAN/MDS_Ansible_Modules#9]
With the below playbook, I can create a zone on NX-OS 8.4(1a) without incident on a pair of 9706's, but the moment I try and run the same playbook on identical MDS's running 8.4(2), it errors stating there are zone locks.
I am able to create these zones by hand without any issue from the CLI directly.
Additionally, if I ghetto comment out the check in the python module for `nxos_zone_zoneset.py` it that checks for locks on the zone, it'll run without incident.
I know that's not a solution, but I had near 500 zones to create by CoB...

ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jaladm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
MDS Modules were just updated.

**Show zone status**
`
VSAN: 102 default-zone: deny distribute: full Interop: default
    mode: enhanced merge-control: allow
    session:  none
    single-session: disabled
    hard-zoning: enabled broadcast: unsupported
    smart-zoning: disabled
    rscn-format: fabric-address
    activation overwrite control: disabled
Default zone:
    qos: none broadcast: unsupported ronly: unsupported
Full Zoning Database :
    DB size: 17912 bytes
    Zonesets:  1 Zones: 108 Aliases: 0 Attribute-groups: 1
Active Zoning Database :
    DB Size: 11580 bytes
    Name: zs102 Zonesets: 1 Zones: 108
Current Total Zone DB Usage: 29492 / 4000000 bytes (0 % used)
Pending (Session) DB size:
    Full DB Copy size: 0 bytes
    Active DB Copy size: 0 bytes
SFC size: 0 / 4000000 bytes (0 % used)
Status: Commit completed at 10:39:55 EDT Jun 11 2020
`

**Begin Playbook**
```

---
- hosts: h1pdsw01
  name: create zones
  connection: network_cli
  gather_facts: no
  vars:
    host: 10.20.6.38
    ansible_ssh_pass: <password>
    iusername: ansibleuser
    ipassword: "{{ ansible_ssh_pass }}"
    transport: cli
  tasks:
    - name: import vars
      include_vars: /etc/ansible/host_vars/10.20.6.38.yml
    - name: Zone it.
      nxos_zone_zoneset:
        zone_zoneset_details:
          - vsan: 101
            mode: enhanced
            smart_zoning: false
            zone:
              - name: 'h1pd04_8742_h1pdpure04_ct00'
                members:
                  - {device-alias: 'h1pd04_8742'}
                  - {device-alias: 'h1pdpure04_ct00'}
            zoneset:
              - name: "zs101"
                members:
                   - {name: 'h1pd04_8742_h1pdpure04_ct00'}
                action: activate


```

--
**Begin error**

```
fatal: [10.20.6.38]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "host": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "zone_zoneset_details": [
                {
                    "default_zone": null,
                    "mode": "enhanced",
                    "smart_zoning": false,
                    "vsan": 101,
                    "zone": [
                        {
                            "members": [
                                {
                                    "device-alias": "h1pd04_8742",
                                    "devtype": null,
                                    "pwwn": "h1pd04_8742",
                                    "remove": false
                                },
                                {
                                    "device-alias": "h1pdpure04_ct00",
                                    "devtype": null,
                                    "pwwn": "h1pdpure04_ct00",
                                    "remove": false
                                }
                            ],
                            "name": "h1pd04_8742_h1pdpure04_ct00",
                            "remove": false
                        }
                    ],
                    "zoneset": [
                        {
                            "action": "activate",
                            "members": [
                                {
                                    "name": "h1pd04_8742_h1pdpure04_ct00",
                                    "remove": false
                                }
                            ],
                            "name": "zs101",
                            "remove": false
                        }
                    ]
                }
            ]
        }
    },
    "msg": "zone has acquired lock on the switch for vsan 101. Hence cannot procced."

```
